### ISSUE TITLE
Ensure ssl_certificate_authorities is configured for ssl_verify_mode 'force_peer'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-logstash#52]
See related: https://github.com/elastic/logstash/pull/6192

**Comment by geerlingguy** [comment]
Should be as simple as adding:

```
ssl_certificate_authorities => '<%=options[:ssl_certificate]%>'
```

To the beats input configuration file.

Error message I get when testing without this:

```
[2020-01-13T16:04:06,406][ERROR][logstash.javapipeline    ][main] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: Using `verify_mode` set to PEER or FORCE_PEER, requires the configuration of `certificate_authorities`>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-beats-6.0.3-java/lib/logstash/inputs/beats.rb:148:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:200:in `block in register_plugins'", "org/jruby/RubyArray.java:1800:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:199:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:304:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:260:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:154:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:109:in `block in start'"], "pipeline.sources"=>["/etc/logstash/conf.d/01-beats-input.conf", "/etc/logstash/conf.d/02-local-syslog-input.conf", "/etc/logstash/conf.d/10-syslog.conf", "/etc/logstash/conf.d/11-nginx.conf", "/etc/logstash/conf.d/12-apache.conf", "/etc/logstash/conf.d/14-solr.conf", "/etc/logstash/conf.d/15-drupal.conf", "/etc/logstash/conf.d/30-elasticsearch-output.conf"], :thread=>"#<Thread:0x3b9654df run>"}
[2020-01-13T16:04:06,436][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2020-01-13T16:04:06,922][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2020-01-13T16:04:11,738][INFO ][logstash.runner          ] Logstash shut down.
```

**Comment by geerlingguy** [comment]
This might still be broken :(

**Comment by geerlingguy** [comment]
Related: https://github.com/geerlingguy/ansible-role-logstash/pull/33
